import Head from 'next/head'
import Footer from '../components/Footer'

import styles from '../styles/Index.module.css'

export default function Blog() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.S. Pescasio | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div className={styles.title}>Blog</div>
          <div>Remaking My Portfolio</div>
          <div>Making My First Portfolio</div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
