import Head from 'next/head'

import styles from '../styles/Index.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.S. Pescasio | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Hello! I'm J.S.</div>
        <div>
          Aspiring software engineer based in Southern California, with a great interest in software and web development.
        </div>
        <div>
          Currently a third-year undergraduate studying computer science at UCR. Let's talk at hello@jspescas.io!
        </div>
      </main>
    </div>
  )
}
