import Head from 'next/head'

import styles from '../styles/Index.module.css'

export default function Projects() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.S. Pescasio | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Projects
        </h1>
      </main>
    </div>
  )
}
