import Head from 'next/head'
import Footer from '../components/Footer'

import styles from '../styles/Index.module.css'

export default function Projects() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.S. Pescasio | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div className={styles.title}>Projects</div>
          <div className={styles.subtitle}>In the Works</div>
          <div>
            Portfolio
          </div>
          <div>
            Cutie Hack Website
          </div>
          <div>
            A Web Planner App
          </div>
          <div>
            DiamondHacks Website
          </div>
          <div className={styles.subtitle}>Upcoming</div>
          <div>
            Citrus Hack Website
          </div>
          <div>
            BioHack Website
          </div>
          <div className={styles.subtitle}>Completed</div>
          <div>
            Dota 2 Analyzer Frontend
          </div>
          <div>
            BioHack Website
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
