import Head from 'next/head'
import Footer from '../components/Footer'

import styles from '../styles/Index.module.css'

export default function Projects() {
  return (
    <div className={styles.container}>
      <Head>
        <title>J.S. Pescasio | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>Projects</div>
        <div>
          In the Works
        </div>
        <div>
          Portfolio
        </div>
        <div>
          Cutie Hack Website
        </div>
        <div>
          A Web Planner App
        </div>
        <div>
          DiamondHacks Website
        </div>
        <div>
          Upcoming
        </div>
        <div>
          Citrus Hack Website
        </div>
        <div>
          BioHack Website
        </div>
        <div>
          Completed
        </div>
        <div>
          Dota 2 Analyzer Frontend
        </div>
        <div>
          BioHack Website
        </div>
      </main>
      <Footer />
    </div>
  )
}
